server:
  port: 8000
  address: 0.0.0.0

springdoc:
  swagger-ui: custom-js=/swagger-custom.js

spring:
  application:
    name: sportevents
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/sportevent
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

token:
  access: hhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdhhhsdjghfjkdhgjfsdh
  refresh: kjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslkkjskgljfkdjsgkldfslk
